# Generated by Django 5.2.4 on 2025-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absencedata',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='absencedata',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='absencedata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='absencedata',
            name='practice',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absencedata',
            name='days',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='absencedata',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
