# Generated by Django 5.2.4 on 2025-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_end_date_absencedata_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=255)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hours', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('status', models.CharField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PracticeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.CharField(max_length=255)),
                ('headcount', models.IntegerField()),
                ('fulltime_hours', models.IntegerField()),
            ],
        ),
    ]
