# Generated by Django 5.2.4 on 2025-07-11 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employeedata_practicedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='leaving_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
