# Generated by Django 5.2.4 on 2025-07-11 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_employeedata_leaving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='leaving_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
