# Generated by Django 5.2.4 on 2025-08-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_employeedata_leaving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencedata',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
