# Generated by Django 5.2.4 on 2025-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_absencedata_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
