# Generated by Django 5.2.4 on 2025-08-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_employeedata_leaving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencedata',
            name='days',
            field=models.IntegerField(),
        ),
    ]
